SCScript.install(function(sc) {
  "use strict";

  require("../Core/Object");

  sc.lang.klass.define("Server", function() {
    // TODO: implements $local
    // TODO: implements $local_
    // TODO: implements $internal
    // TODO: implements $internal_
    // TODO: implements $default
    // TODO: implements $named
    // TODO: implements $named_
    // TODO: implements $set
    // TODO: implements $set_
    // TODO: implements $program
    // TODO: implements $program_
    // TODO: implements $sync_s
    // TODO: implements $sync_s_
    // TODO: implements $default_
    // TODO: implements $new
    // TODO: implements $remote
    // TODO: implements $all
    // TODO: implements $all_
    // TODO: implements $initClass
    // TODO: implements $fromName
    // TODO: implements $resumeThreads
    // TODO: implements $quitAll
    // TODO: implements $killAll
    // TODO: implements $freeAll
    // TODO: implements $hardFreeAll
    // TODO: implements $allRunningServers
    // TODO: implements $scsynth
    // TODO: implements $supernova
    // TODO: implements name
    // TODO: implements addr
    // TODO: implements addr_
    // TODO: implements clientID
    // TODO: implements isLocal
    // TODO: implements inProcess
    // TODO: implements sendQuit
    // TODO: implements sendQuit_
    // TODO: implements remoteControlled
    // TODO: implements remoteControlled_
    // TODO: implements serverRunning
    // TODO: implements serverBooting
    // TODO: implements options
    // TODO: implements options_
    // TODO: implements latency
    // TODO: implements latency_
    // TODO: implements dumpMode
    // TODO: implements notify
    // TODO: implements notified
    // TODO: implements nodeAllocator
    // TODO: implements controlBusAllocator
    // TODO: implements audioBusAllocator
    // TODO: implements bufferAllocator
    // TODO: implements scopeBufferAllocator
    // TODO: implements syncThread
    // TODO: implements syncTasks
    // TODO: implements numUGens
    // TODO: implements numSynths
    // TODO: implements numGroups
    // TODO: implements numSynthDefs
    // TODO: implements avgCPU
    // TODO: implements peakCPU
    // TODO: implements sampleRate
    // TODO: implements actualSampleRate
    // TODO: implements aliveThreadPeriod
    // TODO: implements aliveThreadPeriod_
    // TODO: implements tree
    // TODO: implements tree_
    // TODO: implements window
    // TODO: implements scopeWindow
    // TODO: implements scopeWindow_
    // TODO: implements emacsbuf
    // TODO: implements recordNode
    // TODO: implements recHeaderFormat
    // TODO: implements recHeaderFormat_
    // TODO: implements recSampleFormat
    // TODO: implements recSampleFormat_
    // TODO: implements recChannels
    // TODO: implements recChannels_
    // TODO: implements volume
    // TODO: implements pid
    // TODO: implements init
    // TODO: implements initTree
    // TODO: implements newAllocators
    // TODO: implements newNodeAllocators
    // TODO: implements newBusAllocators
    // TODO: implements newBufferAllocators
    // TODO: implements calcOffset
    // TODO: implements newScopeBufferAllocators
    // TODO: implements nextNodeID
    // TODO: implements nextPermNodeID
    // TODO: implements freePermNodeID
    // TODO: implements sendMsg
    // TODO: implements sendBundle
    // TODO: implements sendRaw
    // TODO: implements sendMsgSync
    // TODO: implements sync
    // TODO: implements schedSync
    // TODO: implements listSendMsg
    // TODO: implements listSendBundle
    // TODO: implements sendSynthDef
    // TODO: implements loadSynthDef
    // TODO: implements loadDirectory
    // TODO: implements serverRunning_
    // TODO: implements wait
    // TODO: implements waitForBoot
    // TODO: implements doWhenBooted
    // TODO: implements bootSync
    // TODO: implements ping
    // TODO: implements addStatusWatcher
    // TODO: implements cachedBuffersDo
    // TODO: implements cachedBufferAt
    // TODO: implements inputBus
    // TODO: implements outputBus
    // TODO: implements startAliveThread
    // TODO: implements stopAliveThread
    // TODO: implements aliveThreadIsRunning
    // TODO: implements boot
    // TODO: implements bootServerApp
    // TODO: implements reboot
    // TODO: implements status
    // TODO: implements notify_
    // TODO: implements sendNotifyRequest
    // TODO: implements dumpOSC
    // TODO: implements quit
    // TODO: implements freeAll
    // TODO: implements openBundle
    // TODO: implements closeBundle
    // TODO: implements makeBundle
    // TODO: implements bind
    // TODO: implements bootInProcess
    // TODO: implements quitInProcess
    // TODO: implements allocSharedControls
    // TODO: implements setSharedControl
    // TODO: implements getSharedControl
    // TODO: implements record
    // TODO: implements pauseRecording
    // TODO: implements stopRecording
    // TODO: implements prepareForRecord
    // TODO: implements cmdPeriod
    // TODO: implements doOnServerTree
    // TODO: implements defaultGroup
    // TODO: implements queryAllNodes
    // TODO: implements printOn
    // TODO: implements storeOn
    // TODO: implements archiveAsCompileString
    // TODO: implements archiveAsObject
    // TODO: implements volume_
    // TODO: implements mute
    // TODO: implements unmute
    // TODO: implements hasShmInterface
    // TODO: implements reorder
    // TODO: implements getControlBusValue
    // TODO: implements getControlBusValues
    // TODO: implements setControlBusValue
    // TODO: implements setControlBusValues
    // TODO: implements asBus
    // TODO: implements asGroup
    // TODO: implements asTarget
    // TODO: implements asNodeID
    // TODO: implements onBootAdd
    // TODO: implements onBootRemove
    // TODO: implements onQuitAdd
    // TODO: implements onQuitRemove
    // TODO: implements meter
    // TODO: implements scope
    // TODO: implements freqscope
    // TODO: implements makeWindow
    // TODO: implements calculateViewBounds
    // TODO: implements makeGui
    // TODO: implements plotTree
    // TODO: implements plotTreeView
  });

});
